/**
 * Created by sunxin on 15/11/13.
 */
exports.dbpath="mongodb://localhost:27017/Boss";
exports.imgpath="/data";
exports.service=[
    {
        method:"GET",
        path:"/user/check",
        param: {
              username:String,
        },
        data:Number
    },
    {
        method:"POST",
        path:"/user/register",
        param: {
            username:String,
            pwd:String,
            name:String,
            age:Number,
            sex:String,
            question:String,
            answer:String
        },
        data:String
    },
    {
        method:"GET",
        path:"/user/info",
        param: {
            username:String,
            pwd:String
        },
        data:{
            _id:String,
            username:String,
            pwd:String,
            name:String,
            age:Number,
            sex:String,
            question:String,
            answer:String,
            photo:String,
            level:[
                {
                    name:String,
                    level:String
                }
            ]
        }
    },
    {
        method:"POST",
        path:"/user/photo",
        param: {
            username:String,
            pwd:String,
            //file:File
        },
        data:String
    },
    {
        method:"PUT",
        path:"/user/editname",
        param: {
            username:String,
            pwd:String,
            name:String
        },
        data:String
    },
    {
        method:"PUT",
        path:"/user/pwd",
        param: {
            username:String,
            pwd:String,
            newpwd:String
        },
        data:String
    },
    {
        method:"GET",
        path:"/user/question",
        param: {
            username:String
        },
        data:String
    },
    {
        method:"PUT",
        path:"/user/reset",
        param: {
            username:String,
            answer:String,
            pwd:String
        },
        data:String
    }
];