platform :ios, '7.0'
pod "SVProgressHUD"
pod "Reachability"
pod "SDWebImage"
pod "pop"
pod "IQKeyboardManager"
pod "AFNetworking", '~> 2.0'
pod "LazyTableView"
pod "LazyPageScrollView"
pod "RunTrace"
